# Generated by Django 3.2.3 on 2021-06-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_id'),
        ('sub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course.course'),
        ),
    ]
