# Generated by Django 3.2.3 on 2021-06-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0002_submodel_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodel',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
