# Generated by Django 3.2.4 on 2021-06-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0003_auto_20210606_1812'),
        ('sub', '0004_rename_is_subscribed_submodel_active'),
    ]

    operations = [
    ]
