# Generated by Django 3.0.5 on 2021-06-07 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210606_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontents',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='course.Course'),
        ),
    ]
