# Generated by Django 3.2 on 2021-06-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210607_2137'),
        ('course', '0007_course_duration'),
    ]

    operations = [
    ]
