# Generated by Django 3.0.5 on 2021-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_merge_0004_auto_20210607_2137_0007_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontents',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='courses/'),
        ),
    ]
